### ISSUE TITLE
Replace PPL

### ISSUE THREAD

**Issue by saraedum** [flatsurf/intervalxt#131]
PPL has trouble with the calls we need for the Boshernitzan criterion (it is extremely slow in the cases that come from unfoldings of pentagons.) We should experiment with other solvers and see whether that makes a difference. Additionally, there's some indication that PPL is leaking memory (or maybe we are not using it correctly.) Let's experiment with cbc, similar to what's done here: https://github.com/mkoeppe/sage-numerical-backends-coin/blob/master/sage_numerical_backends_coin/coin_backend.pyx#L68

**Comment by videlec** [comment]
Did you start something here? I think #137 should also make the code much faster.

If we switch to another solver, we should make sure that the test "does the polyhedron generated by a set of rays contain a line" is available.

**Comment by saraedum** [comment]
We don't need to replace PPL anymore due to #137.
