### ISSUE TITLE
implement RationalLinearSubspace

### ISSUE THREAD

**Issue by videlec** [flatsurf/intervalxt#2]
The Boshernitzan algorithm needs to manipulate rational subspaces V < Q^d. More precisely
- query whether a subspace contains a positive vector
- perform elementary transformations
A class `RationalLinearSubspace` has been declared in `rat_linspace.hh` but lacks implementation.

**Comment by saraedum** [comment]
I think I want to implement this with PPL. This makes `hasNonZeroNonNegativeVector` and `hasPositiveVector` trivial to implement. Swapping variables is not really supported, so I have to keep track of the swaps myself. However, there "affine transformations" which should give me elementary transformations.

**Comment by saraedum** [comment]
I started to work on this at #5.
