### ISSUE TITLE
The id of a Label should be accessible

### ISSUE THREAD

**Issue by videlec** [flatsurf/intervalxt#20]
When considering a label its `id` is also relevant. For example it should appear when printing.

The rationale is that the id remains constant along Zorich induction and allows to identify old sub-intervals to new-subintervals. Moreover, we might have various sub-intervals of the same length and the length is not enough to identify the pairs uniquely. Currently, the id is complicated (impossible?) to access because it is hidden in a private `Implementation` subclass.

**Comment by saraedum** [comment]
The printing code suffixes the Ids when there are multiple labels with the same length. The Id currently is nothing that could be nicely printed. It's just a memory object where the label resides.

I guess you only need this for printing?

**Comment by videlec** [comment]
Now the printing is much nicer as the id are visible together with the lengths. However, in some situation you want to be able to keep track of the intervals within a script not only when printing.

**Comment by saraedum** [comment]
Btw., this can also be worked around similarly to what I wrote in #82:

```python
>>> from pyintervalxt import intervalxt
>>> lengths = intervalxt.sample.Lengths[int]([12, 23, 34])
>>> iet = intervalxt.makeIET(lengths, [1, 0, 2])
>>> lengths.render(iet.top()[0])
'a'
```

I'll build something more convenient…
