### ISSUE TITLE
reduce should not return pairs of Labels but "pointers" to them in the list

### ISSUE THREAD

**Issue by videlec** [flatsurf/intervalxt#21]
In the previous version, it was possible to pass from a `Label` to pointers to their position in the top and bottom intervals. I guess that with the current datastructure it would correspond to a `std::list<Label>::const_iterator`. We need this more precise data in order to cut the interval exchange transformation into two interval exchanges.

**Comment by videlec** [comment]
Though we might not want to expose this in the interface...

**Comment by saraedum** [comment]
We decided to merge this into `induce`.
