### ISSUE TITLE
datastructure for IET decomposition

### ISSUE THREAD

**Issue by videlec** [flatsurf/intervalxt#3]
The decomposition of an IET is a list of
- periodic components
- component with no periodic orbit (certified with Boshernitzan algorithm)
Each component corresponds to a subspace of the initial IET and should carry a base change that refer to the initial IET. This can be encoded by an integral matrix with non-negative coefficients.

**Comment by saraedum** [comment]
This is https://github.com/flatsurf/flatsurf/pull/68/commits/19377626db200d8e84b7c8181f490b3afc8aecee.
