### ISSUE TITLE
Allow comparisons of iet in the Python interface

### ISSUE THREAD

**Issue by videlec** [flatsurf/intervalxt#33]
```
>>> from pyintervalxt import intervalxt
>>> intervalxt.IET((9,2),(1,0)) == intervalxt.IET((9,2),(1,0))
False
```
That would help for testing (instead of relying on the string representation).

Two iet are equal if the permutations and the lengths are equal. Namely we should have
```
>>> intervalxt.IET((1,1,1),(1,0,2)) == intervalxt.IET((1,1,1),(2,1,0))
False
>>> intervalxt.IET((3,2,1),(2,1,0)) == intervalxt.IET((1,2,3),(2,1,0))
False
>>> intervalxt.IET((3,2,1),(2,1,0)) == intervalxt.IET((3,2,1),(1,2,0))
False
```
(even though the first example print identically)

**Comment by saraedum** [comment]
When should they be considered equal though? Essentially when their string representation is the same?

**Comment by videlec** [comment]
I updated the description.

**Comment by saraedum** [comment]
Not sure about this one. I think it makes sense for the `==` operator to also compare labels in general and I do not want to make the Python semantics different from the C++ ones if possible. I can see the appeal for testing of course.

**Comment by videlec** [comment]
Instead of calling it `__eq__(self, other)` I am fine calling it `is_unlabelled_equivalent_to(self, other)`.

**Comment by saraedum** [comment]
Ah, sure, with that I do not see any problem.
