### ISSUE TITLE
which integral matrices to use?

### ISSUE THREAD

**Issue by videlec** [flatsurf/intervalxt#4]
Several algoritms needs access to matrices with integral coefficients (#2, #3)
- echelon forms for canonica form of subspaces (over ZZ and QQ)
- elementary operations and swap
- multiplication (non-critical operation)

Some possibilities
- The `fmpz_mat_h` from flint

**Comment by saraedum** [comment]
I guess the responsibility for this has now mostly shifted to flatsurf which keeps track of coefficients. Is there anything else where we need matrices?

**Comment by videlec** [comment]
Indeed IET will only perform addition and scalar multiplication on "transparent" types. Let us close the issue for now.
